### PR TITLE
Some serious updates

### PR DESCRIPTION
**Pull request by mhenrixon**
Fixed all the tests, fixed references increased version and tweaked all
the load paths.

This is fully upgraded to authlogic 3.0.3, rails 3.0.10 (3.1.0 works as well) and rpx_now *.24. Yours if you want it.

### CODE REVIEW

**Comment by tardate** [comment]
mhenrixon ... someone needed to do this, thanks a bunch for diving in! I'll check it out and merge..

**Comment by mhenrixon** [comment]
I added back the add_base in case someone would still like to use it with rails 2.x. This is now running on production for a couple of sites.

**Comment by jDeppen** [comment]
Is this Rails 3 ready now? I'm upgrading my app to Rails 3.1.1 but authlogic_rpx is still requiring authlogic 2.1.6 and rpx_now 0.6.23

**Comment by mhenrixon** [comment]
I use my own repository : git://github.com/mhenrixon/authlogic_rpx.git

``` ruby
#Gemfile
gem 'authlogic', '= 3.0.3'
gem 'rpx_now', '= 0.6.24'
gem 'authlogic_rpx', git: "git://github.com/mhenrixon/authlogic_rpx.git"
```

We are rails 3.1.1 so it should work for you as well.

**Comment by jDeppen** [comment]
Thank you!!

**Pull request closed without merging**
